"""Verdict logic extraction from debate transcripts."""

import structlog
from pydantic import BaseModel, ConfigDict

from prism.dialectic.debate import DebateTranscript

logger = structlog.get_logger(__name__)


class DebateVerdict(BaseModel):
    """The structured result of the debate logic extraction.

    Attributes:
        finding_id: The ID of the original finding debated.
        is_true_positive: True if the attacker won or there was a high-risk stalemate.
        rationale: The primary argument leading to the conclusion.
        confidence: Float score (0.0 to 1.0) of how certain the engine is.
    """
    model_config = ConfigDict(frozen=True)

    finding_id: str
    is_true_positive: bool
    rationale: str
    confidence: float


class VerdictExtractor:
    """Evaluates a DebateTranscript to produce a formalized verdict."""

    def evaluate(self, transcript: DebateTranscript) -> DebateVerdict:
        """Parse the transcript's final verdict string and format it.

        Args:
            transcript: The transcript generated by the DebateManager.

        Returns:
            A frozen DebateVerdict.
        """
        logger.info("evaluating_transcript", finding_id=transcript.finding_id, verdict=transcript.final_verdict)

        # Base case 1: Defender convinced the Attacker it was an FP
        if transcript.final_verdict == "DEFENDER_WINS_FALSE_POSITIVE":
            return DebateVerdict(
                finding_id=transcript.finding_id,
                is_true_positive=False,
                rationale="The attacker conceded that mitigating factors render this finding unexploitable.",
                confidence=0.9
            )

        # Base case 2: Attacker convinced the Defender it was a TP
        elif transcript.final_verdict == "ATTACKER_WINS_TRUE_POSITIVE":
            return DebateVerdict(
                finding_id=transcript.finding_id,
                is_true_positive=True,
                rationale="The defender conceded that no compensating controls prevent exploitation.",
                confidence=0.95
            )

        # Base case 3: Stalemate (No consensus after MAX_ROUNDS)
        # In security, a stalemate usually defaults to "Flag it for human review as a True Positive".
        return DebateVerdict(
            finding_id=transcript.finding_id,
            is_true_positive=True,
            rationale="The LLM agents reached a stalemate. Flagged as a true positive out of caution for human review.",
            confidence=0.5
        )
